import type { Metadata } from 'next';
import {
  Geist,
  Geist_Mono,
  Bellefair,
  Barlow_Condensed,
  Barlow,
} from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const bellefair = Bellefair({
  variable: '--font-bellefair',
  subsets: ['latin'],
  weight: '400',
});

const barlowCondensed = Barlow_Condensed({
  variable: '--font-barlow-condensed',
  subsets: ['latin'],
  weight: '400',
});

const barlow = Barlow({
  variable: '--font-barlow-normal',
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
